
version: "3.7"

volumes:
  data:

services:

  db:
    build: 
      context: ./database
    restart: always
    environment:
      - POSTGRES_USER=ale
      - POSTGRES_PASSWORD=progetto
      - POSTGRES_DATABASE=db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ale"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - my_net

  db_api:
    build:  
      context: ./db_api
    ports:
      - 5000:5000
    depends_on:
      - db
    networks:
      - my_net

  website_progetto:
    build: 
      context: ./website
    ports:
      - 5001:5001
    depends_on:
      - db
      - db_api
    networks:
      - my_net

networks:
  my_net:
    driver: bridge



